<!DOCTYPE html>
<html>
<head>
    <title>SOLICITUD</title>
</head>
<body>
    <p>EL ÁREA DE PERSONAS CON DISCAPACIDAD DEL SISTEMA DIF DEL MUNICIPIO DE SANTA CRUZ
        XOXOCOTLÁN OAXACA, SOLICITA DE LA MANERA MÁS ATENTA ATENDER LA SIGUIENTE SOLICITUD


        </p>
</body>
</html>
